steps:
  - name: "gcr.io/cloud-builders/docker"
    dir: "."
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/smover-backend/cms:$SHORT_SHA"
      - "-f"
      - "./Dockerfile"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/smover-backend/cms:$SHORT_SHA"

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "cms"
      - "--region=us-central1"
      - "--platform=managed"
      - "--image=gcr.io/$PROJECT_ID/smover-backend/cms:$SHORT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s
